// База вопросов на русском и английском языках.
// Формат элемента: { q, options: [..4], correctIndex, tip }

const QUESTIONS_RU = [
  { q: 'Что такое IBM Planning Analytics (TM1)?', options: ['OLAP-платформа для планирования и аналитики', 'СУБД для транзакций', 'Инструмент ETL только для CSV', 'BI-портал без расчётов'], correctIndex: 0, tip: 'OLAP-кубы, планы, бюджеты' },
  { q: 'Как называется язык правил в TM1?', options: ['TurboIntegrator', 'MDX', 'Rules', 'DAX'], correctIndex: 2, tip: 'Правила задаются в cube.rules' },
  { q: 'Где хранятся исходные данные TM1 по умолчанию?', options: ['В реляционной БД', 'В плоских файлах на диске', 'В памяти сервера', 'Только в облаке'], correctIndex: 2, tip: 'In-memory OLAP' },
  { q: 'Что делает TurboIntegrator в TM1?', options: ['Определяет права', 'Формирует отчёты', 'Автоматизирует загрузку/преобразование данных', 'Мониторит сервер'], correctIndex: 2, tip: 'ETL-скрипты TI' },
  { q: 'MDX в контексте TM1 — это:', options: ['Язык для кубических запросов', 'Средство администрирования', 'Формат хранения', 'План-график задач'], correctIndex: 0, tip: 'Многомерные запросы' },
  { q: 'Объект TM1 для измерений — это:', options: ['Cube', 'Dimension', 'Subset', 'Process'], correctIndex: 1, tip: 'Список элементов (Members)' },
  { q: 'Как называется поднабор элементов измерения?', options: ['Subset', 'Hierarchy', 'Attribute', 'Sandbox'], correctIndex: 0, tip: 'Фильтрация members' },
  { q: 'Где задаются вычисляемые зависимости ячеек?', options: ['В TI процессах', 'В правилах куба', 'В подсетах', 'В атрибутах'], correctIndex: 1, tip: 'Rules для куба' },
  { q: 'Что такое Sandbox в TM1?', options: ['Изолированная область для моделирования', 'Роль безопасности', 'Тип процесса', 'Отчёт'], correctIndex: 0, tip: 'Песочница для «что если»' },
  { q: 'Какой объект описывает многомерные данные?', options: ['Cube', 'View', 'Chore', 'Process'], correctIndex: 0, tip: 'Куб — факт. таблица' },
  { q: 'View в TM1 — это:', options: ['Материализованный отчёт', 'Сохранённый срез представления куба', 'ETL-процесс', 'Поднабор измерения'], correctIndex: 1, tip: 'Выбор осей, фильтров' },
  { q: 'Attribute у элемента измерения — это:', options: ['Значение факта', 'Метаданные/свойства элемента', 'Роль', 'ETL'], correctIndex: 1, tip: 'Напр. Тип, Код' },
  { q: 'Chore — это:', options: ['Расписание процессов', 'Правило безопасности', 'Поднабор', 'Измерение'], correctIndex: 0, tip: 'Планировщик TI' },
  { q: 'Security в TM1 управляет:', options: ['Производительностью', 'Доступом и правами', 'Валютацией', 'MDX'], correctIndex: 1, tip: 'Группы и роли' },
  { q: 'В TM1 правило комментируется:', options: ['// или #', '/* */', '--', 'Нет комментариев'], correctIndex: 0, tip: 'Как в C-подобных' },
  { q: 'ProcessErrorFile в TI — это:', options: ['Лог ошибок процесса', 'Файл данных', 'MDX-скрипт', 'Правило'], correctIndex: 0, tip: 'Смотрим ошибки здесь' },
  { q: 'TM1 поддерживает иерархии:', options: ['Только плоские', 'Только один уровень', 'Многоуровневые (родитель-ребёнок)', 'Только атрибутные'], correctIndex: 2, tip: 'Roll-up уровни' },
  { q: 'Cube Feeder — это:', options: ['Оптимизатор памяти', 'Механизм подсветки правил', 'Механизм «кормления» зависимостей', 'Уведомления'], correctIndex: 2, tip: 'Feeders для спарсенных ячеек' },
  { q: 'Что ускоряет вычисление правил?', options: ['Feeders', 'Subsets', 'Attributes', 'Chores'], correctIndex: 0, tip: 'Указывают, какие клетки активны' },
  { q: 'Среда для пользовательских панелей:', options: ['PAW (Workspace)', 'Excel только', 'Notes', 'DB2'], correctIndex: 0, tip: 'Планшеты, дашборды' },
  { q: 'PAfE расшифровывается как:', options: ['Planning Analytics for Excel', 'Platform for ETL', 'Portal and Feeds', 'PA for Edge'], correctIndex: 0, tip: 'Адд-ин Excel' },
  { q: 'TI-процессы пишутся на:', options: ['Python', 'Своём скриптовом языке TI', 'Java', 'SQL'], correctIndex: 1, tip: 'Встроенный язык' },
  { q: 'MDX можно использовать для:', options: ['Создания подсетов', 'Определения прав', 'Логирования', 'Feeders'], correctIndex: 0, tip: 'Dynamic subsets' },
  { q: 'Куда писать логи TI по умолчанию?', options: ['tm1server.log', 'tm1process.log', 'ti.log', 'processerror.log'], correctIndex: 1, tip: 'Отдельный лог процессов' },
  { q: 'Куда писать ошибки TI?', options: ['tm1server.log', 'tm1processerror.log', 'tm1error.log', 'tm1feeders.log'], correctIndex: 1, tip: 'Файл ошибок процессов' },
  { q: 'Rule в TM1 применяется к:', options: ['Всей БД', 'Конкретному кубу', 'Измерению', 'Поднабору'], correctIndex: 1, tip: 'Файл cube.rules' },
  { q: 'Первичная единица данных TM1:', options: ['Ячейка', 'Строка', 'Документ', 'Процесс'], correctIndex: 0, tip: 'Cell в кубе' },
  { q: 'Что такое Leaf элементы?', options: ['Итоговые члены', 'Базовые члены без потомков', 'Атрибуты', 'Поднабор'], correctIndex: 1, tip: 'Листья иерархии' },
  { q: 'На что влияет Skipcheck?', options: ['Безопасность', 'Порядок обработки', 'Оптимизацию правил', 'Расписание'], correctIndex: 2, tip: 'С правилами' },
  { q: 'Сервис TM1 — это:', options: ['tm1sd.exe', 'PAW', 'Gateway', 'Cognos Controller'], correctIndex: 0, tip: 'Серверный процесс' },
  { q: 'Cube View экспорт в CSV делается через:', options: ['Правила', 'TI-процессы', 'MDX', 'PAW'], correctIndex: 1, tip: 'Процесс выгрузки' },
  { q: 'Отчёты в PAW строятся на:', options: ['Кубах TM1', 'Только SQL', 'Google Sheets', 'Power BI'], correctIndex: 0, tip: 'Нативная интеграция' },
  { q: 'Что такое CellSecurity?', options: ['Атрибут', 'Модель прав на уровне ячейки', 'Поднабор', 'TI-процесс'], correctIndex: 1, tip: 'Точечные права' },
  { q: 'Для импорта измерения из CSV используем:', options: ['Rules', 'Chore', 'TI-процесс', 'MDX'], correctIndex: 2, tip: 'Импорт и обновление' },
  { q: 'Переагрегация значений идёт по:', options: ['Иерархии измерений', 'Поднаборам', 'Атрибутам', 'TI-процессам'], correctIndex: 0, tip: 'Roll-up' },
  { q: 'Порог «Sparse Consolidation» связан с:', options: ['Плотными кубами', 'Разрежённостью данных', 'Безопасностью', 'Планировщиком'], correctIndex: 1, tip: 'Sparse модели' },
  { q: 'Параметр ServerSandboxEnabled управляет:', options: ['Версионированием', 'Песочницами', 'MDX', 'TI Log'], correctIndex: 1, tip: 'Сценарии What-If' },
  { q: 'Hierarchy в TM1 — это:', options: ['Альт. иерархии измерения', 'Внешняя БД', 'Поднабор', 'Правило'], correctIndex: 0, tip: 'Alternate hierarchies' },
  { q: 'Cube Drill-through — это:', options: ['Переход к деталям', 'Смена подсета', 'Экспорт в XLSX', 'Смена ролей'], correctIndex: 0, tip: 'Drill к источнику' },
  { q: 'Параметр SecurityRefreshInterval:', options: ['Кэш атрибутов', 'Интервал обновления безопасности', 'MDX буфер', 'TI таймаут'], correctIndex: 1, tip: 'Права актуализируются' },
  { q: 'TM1 сервер чаще всего разворачивают на:', options: ['Windows/Linux', 'iOS', 'Android', 'Mainframe'], correctIndex: 0, tip: 'Серверная ОС' },
  { q: 'Планировщик задач в TM1 — это:', options: ['Chores', 'Rules', 'Subsets', 'Attributes'], correctIndex: 0, tip: 'Расписания' },
  { q: 'Cube Logging нужен для:', options: ['Аудита изменений ячеек', 'MDX оптимизаций', 'UI темизации', 'Backup'], correctIndex: 0, tip: 'Лог изменений' },
  { q: 'TI-функция ASCIIOutput делает:', options: ['Импорт', 'Экспорт в текстовый файл', 'Права', 'Запуск MDX'], correctIndex: 1, tip: 'Запись в файл' },
  { q: 'Слой визуализации PAW работает через:', options: ['Веб', 'WinForms', 'Thick client', 'SSH'], correctIndex: 0, tip: 'Браузерные панели' },
  { q: 'Правила применяются к ячейкам:', options: ['Только на ввод', 'Динамически при обращении', 'Только при загрузке', 'Только в PAfE'], correctIndex: 1, tip: 'On-demand calc' },
  { q: 'Exploration в PAW — это:', options: ['Кубический анализ', 'ETL', 'MDX редактор', 'Security UI'], correctIndex: 0, tip: 'Исследование данных' },
  { q: 'Справочник пользователей хранится в:', options: ['TM1 встроенно', 'LDAP/AD интеграция', 'CSV', 'MDX'], correctIndex: 1, tip: 'Корп. каталог' },
  { q: 'CubeViewCreate делает:', options: ['Создаёт представление куба', 'Создаёт TI-процесс', 'Создаёт измерение', 'Создаёт chore'], correctIndex: 0, tip: 'API/скрипты' },
  { q: 'Какой объект хранит бизнес-логику расчёта?', options: ['Rules', 'Chores', 'Subsets', 'Attributes'], correctIndex: 0, tip: 'Файл правил куба' },
  { q: 'Что такое Consolidation?', options: ['Свертка значений по иерархии', 'Архивация данных', 'Смена окружения', 'Обновление прав'], correctIndex: 0, tip: 'Итоговые уровни' },
  { q: 'Какая роль у Feeders?', options: ['Определяют активные клетки для правил', 'Импорт CSV', 'UI навигация', 'MDX фильтрация'], correctIndex: 0, tip: 'Производительность' },
  { q: 'Что такое PAW Book?', options: ['Набор пнелей/видов', 'Резервная копия', 'Правило', 'TI-процесс'], correctIndex: 0, tip: 'Книга с листами' },
  { q: 'TM1 поддерживает расчет по требованию?', options: ['Да', 'Нет', 'Только в PAfE', 'Только в PAW'], correctIndex: 0, tip: 'Lazy calculation' },
  { q: 'С помощью чего делаем расписание запуска TI?', options: ['Chore', 'Rule', 'Subset', 'MDX'], correctIndex: 0, tip: 'Планировщик' },
  { q: 'Где удобно вводить плановые данные?', options: ['PAfE/PAW', 'БД напрямую', 'MDX окно', 'TI лог'], correctIndex: 0, tip: 'Excel и Web' },
  { q: 'Что лучше для динамических подсетов?', options: ['MDX', 'TI', 'Rules', 'CSV'], correctIndex: 0, tip: 'MDX выражения' },
  { q: 'Какой файл хранит логи сервера?', options: ['tm1server.log', 'tm1process.log', 'tm1mdx.log', 'tm1access.log'], correctIndex: 0, tip: 'Основной лог' },
  { q: 'Чем отличается Leaf от Consolidated?', options: ['Leaf — базовый элемент, Consolidated — агрегат', 'Разницы нет', 'Оба базовые', 'Оба агрегаты'], correctIndex: 0, tip: 'Иерархии' },
];

const QUESTIONS_EN = [
  { q: 'What is IBM Planning Analytics (TM1)?', options: ['An OLAP platform for planning and analytics', 'A transactional database', 'An ETL tool only for CSV files', 'A BI portal without calculations'], correctIndex: 0, tip: 'OLAP cubes, plans, budgets' },
  { q: 'What is the rules language in TM1 called?', options: ['TurboIntegrator', 'MDX', 'Rules', 'DAX'], correctIndex: 2, tip: 'Rules live in cube.rules' },
  { q: 'Where are TM1 source data stored by default?', options: ['In a relational DB', 'In flat files on disk', 'In server memory', 'Only in the cloud'], correctIndex: 2, tip: 'In-memory OLAP' },
  { q: 'What does TurboIntegrator do in TM1?', options: ['Defines security', 'Builds reports', 'Automates data load/transformation', 'Monitors the server'], correctIndex: 2, tip: 'TI ETL scripts' },
  { q: 'MDX in TM1 is:', options: ['A language for cube queries', 'An administration tool', 'A storage format', 'A job schedule'], correctIndex: 0, tip: 'Multidimensional queries' },
  { q: 'Which TM1 object stores dimensions?', options: ['Cube', 'Dimension', 'Subset', 'Process'], correctIndex: 1, tip: 'List of members' },
  { q: 'How is a subset of dimension elements called?', options: ['Subset', 'Hierarchy', 'Attribute', 'Sandbox'], correctIndex: 0, tip: 'Filtered members' },
  { q: 'Where are cell dependencies defined?', options: ['In TI processes', 'In cube rules', 'In subsets', 'In attributes'], correctIndex: 1, tip: 'Cube rules' },
  { q: 'What is a Sandbox in TM1?', options: ['An isolated what-if area', 'A security role', 'A process type', 'A report'], correctIndex: 0, tip: 'What-if sandbox' },
  { q: 'Which object represents multidimensional data?', options: ['Cube', 'View', 'Chore', 'Process'], correctIndex: 0, tip: 'Cube = fact table' },
  { q: 'A View in TM1 is:', options: ['A materialized report', 'A saved cube slice', 'An ETL process', 'A subset'], correctIndex: 1, tip: 'Axes and filters' },
  { q: 'An attribute of a dimension element is:', options: ['A fact value', 'Metadata/properties', 'A role', 'ETL'], correctIndex: 1, tip: 'Type, Code etc.' },
  { q: 'A Chore is:', options: ['A process schedule', 'A security rule', 'A subset', 'A dimension'], correctIndex: 0, tip: 'TI scheduler' },
  { q: 'Security in TM1 controls:', options: ['Performance', 'Access and permissions', 'Valuation', 'MDX'], correctIndex: 1, tip: 'Groups and roles' },
  { q: 'How do you comment a rule in TM1?', options: ['// or #', '/* */', '--', 'No comments'], correctIndex: 0, tip: 'C-style comments' },
  { q: 'ProcessErrorFile in TI is:', options: ['A process error log', 'A data file', 'An MDX script', 'A rule'], correctIndex: 0, tip: 'Check errors here' },
  { q: 'What hierarchies does TM1 support?', options: ['Only flat ones', 'Single level only', 'Multi-level parent-child', 'Attribute-only'], correctIndex: 2, tip: 'Roll-up levels' },
  { q: 'Cube Feeders are:', options: ['Memory optimizers', 'Rule highlighting', 'Dependency feeders', 'Notifications'], correctIndex: 2, tip: 'Feed sparse cells' },
  { q: 'What speeds up rule evaluation?', options: ['Feeders', 'Subsets', 'Attributes', 'Chores'], correctIndex: 0, tip: 'Mark active cells' },
  { q: 'Workspace for user dashboards is:', options: ['PAW (Workspace)', 'Excel only', 'Notes', 'DB2'], correctIndex: 0, tip: 'Dashboards' },
  { q: 'PAfE stands for:', options: ['Planning Analytics for Excel', 'Platform for ETL', 'Portal and Feeds', 'Planning Analytics for Edge'], correctIndex: 0, tip: 'Excel add-in' },
  { q: 'TI processes are written in:', options: ['Python', 'The TI scripting language', 'Java', 'SQL'], correctIndex: 1, tip: 'Built-in language' },
  { q: 'MDX can be used for:', options: ['Building subsets', 'Defining security', 'Logging', 'Feeders'], correctIndex: 0, tip: 'Dynamic subsets' },
  { q: 'Where do TI logs go by default?', options: ['tm1server.log', 'tm1process.log', 'ti.log', 'processerror.log'], correctIndex: 1, tip: 'Process log' },
  { q: 'Where do TI errors go?', options: ['tm1server.log', 'tm1processerror.log', 'tm1error.log', 'tm1feeders.log'], correctIndex: 1, tip: 'Process errors file' },
  { q: 'A rule in TM1 applies to:', options: ['The whole database', 'A specific cube', 'A dimension', 'A subset'], correctIndex: 1, tip: 'cube.rules' },
  { q: 'Primary data unit in TM1:', options: ['Cell', 'Row', 'Document', 'Process'], correctIndex: 0, tip: 'Cube cell' },
  { q: 'What are Leaf elements?', options: ['Consolidated members', 'Base members without children', 'Attributes', 'Subsets'], correctIndex: 1, tip: 'Hierarchy leaves' },
  { q: 'Skipcheck affects:', options: ['Security', 'Processing order', 'Rule optimization', 'Scheduling'], correctIndex: 2, tip: 'Rules behavior' },
  { q: 'The TM1 service is:', options: ['tm1sd.exe', 'PAW', 'Gateway', 'Cognos Controller'], correctIndex: 0, tip: 'Server process' },
  { q: 'How do you export a cube view to CSV?', options: ['Rules', 'TI processes', 'MDX', 'PAW'], correctIndex: 1, tip: 'Export process' },
  { q: 'PAW reports are built on:', options: ['TM1 cubes', 'SQL only', 'Google Sheets', 'Power BI'], correctIndex: 0, tip: 'Native integration' },
  { q: 'What is CellSecurity?', options: ['An attribute', 'Cell-level security model', 'A subset', 'A TI process'], correctIndex: 1, tip: 'Granular rights' },
  { q: 'To import a dimension from CSV we use:', options: ['Rules', 'Chores', 'A TI process', 'MDX'], correctIndex: 2, tip: 'Import/update' },
  { q: 'Re-aggregation of values happens along:', options: ['Dimension hierarchies', 'Subsets', 'Attributes', 'TI processes'], correctIndex: 0, tip: 'Roll-up' },
  { q: 'The "Sparse Consolidation" threshold relates to:', options: ['Dense cubes', 'Data sparsity', 'Security', 'Scheduler'], correctIndex: 1, tip: 'Sparse models' },
  { q: 'ServerSandboxEnabled parameter controls:', options: ['Versioning', 'Sandboxes', 'MDX', 'TI log'], correctIndex: 1, tip: 'What-if scenarios' },
  { q: 'A Hierarchy in TM1 is:', options: ['An alternate dimension hierarchy', 'An external DB', 'A subset', 'A rule'], correctIndex: 0, tip: 'Alternate hierarchies' },
  { q: 'Cube drill-through is:', options: ['Jumping to detailed data', 'Switching subsets', 'Exporting to XLSX', 'Switching roles'], correctIndex: 0, tip: 'Drill to source' },
  { q: 'SecurityRefreshInterval controls:', options: ['Attribute cache', 'Security refresh interval', 'MDX buffer', 'TI timeout'], correctIndex: 1, tip: 'Update security' },
  { q: 'TM1 servers usually run on:', options: ['Windows/Linux', 'iOS', 'Android', 'Mainframes'], correctIndex: 0, tip: 'Server OS' },
  { q: 'The TM1 task scheduler is:', options: ['Chores', 'Rules', 'Subsets', 'Attributes'], correctIndex: 0, tip: 'Schedules' },
  { q: 'Cube logging is for:', options: ['Auditing cell changes', 'MDX optimization', 'UI theming', 'Backup'], correctIndex: 0, tip: 'Change log' },
  { q: 'TI function ASCIIOutput does:', options: ['Import', 'Export to a text file', 'Security', 'Run MDX'], correctIndex: 1, tip: 'Write to file' },
  { q: 'PAW visualization layer works via:', options: ['Web', 'WinForms', 'Thick client', 'SSH'], correctIndex: 0, tip: 'Browser panels' },
  { q: 'Rules are applied to cells:', options: ['Only on input', 'Dynamically on demand', 'Only on load', 'Only in PAfE'], correctIndex: 1, tip: 'Calculated on demand' },
  { q: 'Exploration in PAW is:', options: ['Cube exploration', 'ETL', 'MDX editor', 'Security UI'], correctIndex: 0, tip: 'Data exploration' },
  { q: 'User directories are stored in:', options: ['Built-in TM1', 'LDAP/AD integration', 'CSV', 'MDX'], correctIndex: 1, tip: 'Corporate directory' },
  { q: 'CubeViewCreate does:', options: ['Creates a cube view', 'Creates a TI process', 'Creates a dimension', 'Creates a chore'], correctIndex: 0, tip: 'API/scripts' },
  { q: 'Which object stores calculation logic?', options: ['Rules', 'Chores', 'Subsets', 'Attributes'], correctIndex: 0, tip: 'Cube rule file' },
  { q: 'What is consolidation?', options: ['Rolling up values along a hierarchy', 'Archiving data', 'Switching environments', 'Updating security'], correctIndex: 0, tip: 'Totals' },
  { q: 'What do Feeders do?', options: ['Mark active cells for rules', 'Import CSV', 'UI navigation', 'MDX filtering'], correctIndex: 0, tip: 'Performance' },
  { q: 'What is a PAW Book?', options: ['A set of panels/views', 'A backup copy', 'A rule', 'A TI process'], correctIndex: 0, tip: 'Workbook with sheets' },
  { q: 'Does TM1 support calculation on demand?', options: ['Yes', 'No', 'Only in PAfE', 'Only in PAW'], correctIndex: 0, tip: 'Lazy calculation' },
  { q: 'How do you schedule TI execution?', options: ['Chore', 'Rule', 'Subset', 'MDX'], correctIndex: 0, tip: 'Scheduler' },
  { q: 'Where is it convenient to enter plan data?', options: ['PAfE/PAW', 'Directly in the DB', 'MDX window', 'TI log'], correctIndex: 0, tip: 'Excel and web' },
  { q: 'What is best for dynamic subsets?', options: ['MDX', 'TI', 'Rules', 'CSV'], correctIndex: 0, tip: 'MDX expressions' },
  { q: 'Which file stores server logs?', options: ['tm1server.log', 'tm1process.log', 'tm1mdx.log', 'tm1access.log'], correctIndex: 0, tip: 'Main log' },
  { q: 'How do Leaf and Consolidated differ?', options: ['Leaf is a base element, Consolidated is an aggregate', 'No difference', 'Both are base', 'Both are aggregates'], correctIndex: 0, tip: 'Hierarchy roles' },
];

window.QUESTIONS_DB_BY_LANG = { ru: QUESTIONS_RU, en: QUESTIONS_EN };
window.QUESTIONS_DB = QUESTIONS_RU;
