// База из 50 вопросов. Формат: { q, options: [..4], correctIndex, tip }
// Замените тексты на свои. Сейчас вопросы-темплейты по теме Cognos TM1.

const QUESTIONS_DB = [
	{ q: 'Что такое IBM Planning Analytics (TM1)?', options: ['OLAP-платформа для планирования и аналитики', 'СУБД для транзакций', 'Инструмент ETL только для CSV', 'BI-портал без расчётов'], correctIndex: 0, tip: 'OLAP-кубы, планы, бюджеты' },
	{ q: 'Как называется язык правил в TM1?', options: ['TurboIntegrator', 'MDX', 'Rules', 'DAX'], correctIndex: 2, tip: 'Правила задаются в cube.rules' },
	{ q: 'Где хранятся исходные данные TM1 по умолчанию?', options: ['В реляционной БД', 'В плоских файлах на диске', 'В памяти сервера', 'Только в облаке'], correctIndex: 2, tip: 'In-memory OLAP' },
	{ q: 'Что делает TurboIntegrator в TM1?', options: ['Определяет права', 'Формирует отчёты', 'Автоматизирует загрузку/преобразование данных', 'Мониторит сервер'], correctIndex: 2, tip: 'ETL-скрипты TI' },
	{ q: 'MDX в контексте TM1 — это:', options: ['Язык для кубических запросов', 'Средство администрирования', 'Формат хранения', 'План-график задач'], correctIndex: 0, tip: 'Многомерные запросы' },
	{ q: 'Объект TM1 для измерений — это:', options: ['Cube', 'Dimension', 'Subset', 'Process'], correctIndex: 1, tip: 'Список элементов (Members)' },
	{ q: 'Как называется поднабор элементов измерения?', options: ['Subset', 'Hierarchy', 'Attribute', 'Sandbox'], correctIndex: 0, tip: 'Фильтрация members' },
	{ q: 'Где задаются вычисляемые зависимости ячеек?', options: ['В TI процессах', 'В правилах куба', 'В подсетах', 'В атрибутах'], correctIndex: 1, tip: 'Rules для куба' },
	{ q: 'Что такое Sandbox в TM1?', options: ['Изолированная область для моделирования', 'Роль безопасности', 'Тип процесса', 'Отчёт'], correctIndex: 0, tip: 'Песочница для «что если»' },
	{ q: 'Какой объект описывает многомерные данные?', options: ['Cube', 'View', 'Chore', 'Process'], correctIndex: 0, tip: 'Куб — факт. таблица' },
	{ q: 'View в TM1 — это:', options: ['Материализованный отчёт', 'Сохранённый срез представления куба', 'ETL-процесс', 'Поднабор измерения'], correctIndex: 1, tip: 'Выбор осей, фильтров' },
	{ q: 'Attribute у элемента измерения — это:', options: ['Значение факта', 'Метаданные/свойства элемента', 'Роль', 'ETL'], correctIndex: 1, tip: 'Напр. Тип, Код' },
	{ q: 'Chore — это:', options: ['Расписание процессов', 'Правило безопасности', 'Поднабор', 'Измерение'], correctIndex: 0, tip: 'Планировщик TI' },
	{ q: 'Security в TM1 управляет:', options: ['Производительностью', 'Доступом и правами', 'Валютацией', 'MDX'], correctIndex: 1, tip: 'Группы и роли' },
	{ q: 'В TM1 правило комментируется:', options: ['// или #', '/* */', '--', 'Нет комментариев'], correctIndex: 0, tip: 'Как в C-подобных' },
	{ q: 'ProcessErrorFile в TI — это:', options: ['Лог ошибок процесса', 'Файл данных', 'MDX-скрипт', 'Правило'], correctIndex: 0, tip: 'Смотрим ошибки здесь' },
	{ q: 'TM1 поддерживает иерархии:', options: ['Только плоские', 'Только один уровень', 'Многоуровневые (родитель-ребёнок)', 'Только атрибутные'], correctIndex: 2, tip: 'Roll-up уровни' },
	{ q: 'Cube Feeder — это:', options: ['Оптимизатор памяти', 'Механизм подсветки правил', 'Механизм «кормления» зависимостей', 'Уведомления'], correctIndex: 2, tip: 'Feeders для спарсенных ячеек' },
	{ q: 'Что ускоряет вычисление правил?', options: ['Feeders', 'Subsets', 'Attributes', 'Chores'], correctIndex: 0, tip: 'Указывают, какие клетки активны' },
	{ q: 'Среда для пользовательских панелей:', options: ['PAW (Workspace)', 'Excel только', 'Notes', 'DB2'], correctIndex: 0, tip: 'Планшеты, дашборды' },
	{ q: 'PAfE расшифровывается как:', options: ['Planning Analytics for Excel', 'Platform for ETL', 'Portal and Feeds', 'PA for Edge'], correctIndex: 0, tip: 'Адд-ин Excel' },
	{ q: 'TI-процессы пишутся на:', options: ['Python', 'Своём скриптовом языке TI', 'Java', 'SQL'], correctIndex: 1, tip: 'Встроенный язык' },
	{ q: 'MDX можно использовать для:', options: ['Создания подсетов', 'Определения прав', 'Логирования', 'Feeders'], correctIndex: 0, tip: 'Dynamic subsets' },
	{ q: 'Куда писать логи TI по умолчанию?', options: ['tm1server.log', 'tm1process.log', 'ti.log', 'processerror.log'], correctIndex: 1, tip: 'Отдельный лог процессов' },
	{ q: 'Куда писать ошибки TI?', options: ['tm1server.log', 'tm1processerror.log', 'tm1error.log', 'tm1feeders.log'], correctIndex: 1, tip: 'Файл ошибок процессов' },
	{ q: 'Rule в TM1 применяется к:', options: ['Всей БД', 'Конкретному кубу', 'Измерению', 'Поднабору'], correctIndex: 1, tip: 'Файл cube.rules' },
	{ q: 'Первичная единица данных TM1:', options: ['Ячейка', 'Строка', 'Документ', 'Процесс'], correctIndex: 0, tip: 'Cell в кубе' },
	{ q: 'Что такое Leaf элементы?', options: ['Итоговые члены', 'Базовые члены без потомков', 'Атрибуты', 'Поднабор'], correctIndex: 1, tip: 'Листья иерархии' },
	{ q: 'На что влияет Skipcheck?', options: ['Безопасность', 'Порядок обработки', 'Оптимизацию правил', 'Расписание'], correctIndex: 2, tip: 'С правилами' },
	{ q: 'Сервис TM1 — это:', options: ['tm1sd.exe', 'PAW', 'Gateway', 'Cognos Controller'], correctIndex: 0, tip: 'Серверный процесс' },
	{ q: 'Cube View экспорт в CSV делается через:', options: ['Правила', 'TI-процессы', 'MDX', 'PAW'], correctIndex: 1, tip: 'Процесс выгрузки' },
	{ q: 'Отчёты в PAW строятся на:', options: ['Кубах TM1', 'Только SQL', 'Google Sheets', 'Power BI'], correctIndex: 0, tip: 'Нативная интеграция' },
	{ q: 'Что такое CellSecurity?', options: ['Атрибут', 'Модель прав на уровне ячейки', 'Поднабор', 'TI-процесс'], correctIndex: 1, tip: 'Точечные права' },
	{ q: 'Для импорта измерения из CSV используем:', options: ['Rules', 'Chore', 'TI-процесс', 'MDX'], correctIndex: 2, tip: 'Импорт и обновление' },
	{ q: 'Переагрегация значений идёт по:', options: ['Иерархии измерений', 'Поднаборам', 'Атрибутам', 'TI-процессам'], correctIndex: 0, tip: 'Roll-up' },
	{ q: 'Порог «Sparse Consolidation» связан с:', options: ['Плотными кубами', 'Разрежённостью данных', 'Безопасностью', 'Планировщиком'], correctIndex: 1, tip: 'Sparse модели' },
	{ q: 'Параметр ServerSandboxEnabled управляет:', options: ['Версионированием', 'Песочницами', 'MDX', 'TI Log'], correctIndex: 1, tip: 'Сценарии What-If' },
	{ q: 'Hierarchy в TM1 — это:', options: ['Альт. иерархии измерения', 'Внешняя БД', 'Поднабор', 'Правило'], correctIndex: 0, tip: 'Alternate hierarchies' },
	{ q: 'Cube Drill-through — это:', options: ['Переход к деталям', 'Смена подсета', 'Экспорт в XLSX', 'Смена ролей'], correctIndex: 0, tip: 'Drill к источнику' },
	{ q: 'Параметр SecurityRefreshInterval:', options: ['Кэш атрибутов', 'Интервал обновления безопасности', 'MDX буфер', 'TI таймаут'], correctIndex: 1, tip: 'Права актуализируются' },
	{ q: 'TM1 сервер чаще всего разворачивают на:', options: ['Windows/Linux', 'iOS', 'Android', 'Mainframe'], correctIndex: 0, tip: 'Серверная ОС' },
	{ q: 'Планировщик задач в TM1 — это:', options: ['Chores', 'Rules', 'Subsets', 'Attributes'], correctIndex: 0, tip: 'Расписания' },
	{ q: 'Cube Logging нужен для:', options: ['Аудита изменений ячеек', 'MDX оптимизаций', 'UI темизации', 'Backup'], correctIndex: 0, tip: 'Лог изменений' },
	{ q: 'TI-функция ASCIIOutput делает:', options: ['Импорт', 'Экспорт в текстовый файл', 'Права', 'Запуск MDX'], correctIndex: 1, tip: 'Запись в файл' },
	{ q: 'Слой визуализации PAW работает через:', options: ['Веб', 'WinForms', 'Thick client', 'SSH'], correctIndex: 0, tip: 'Браузерные панели' },
	{ q: 'Правила применяются к ячейкам:', options: ['Только на ввод', 'Динамически при обращении', 'Только при загрузке', 'Только в PAfE'], correctIndex: 1, tip: 'On-demand calc' },
	{ q: 'Exploration в PAW — это:', options: ['Кубический анализ', 'ETL', 'MDX редактор', 'Security UI'], correctIndex: 0, tip: 'Исследование данных' },
	{ q: 'Справочник пользователей хранится в:', options: ['TM1 встроенно', 'LDAP/AD интеграция', 'CSV', 'MDX'], correctIndex: 1, tip: 'Корп. каталог' },
	{ q: 'CubeViewCreate делает:', options: ['Создаёт представление куба', 'Создаёт TI-процесс', 'Создаёт измерение', 'Создаёт chore'], correctIndex: 0, tip: 'API/скрипты' },
	{ q: 'Какой объект хранит бизнес-логику расчёта?', options: ['Rules', 'Chores', 'Subsets', 'Attributes'], correctIndex: 0, tip: 'Файл правил куба' },
	{ q: 'Что такое Consolidation?', options: ['Свертка значений по иерархии', 'Архивация данных', 'Смена окружения', 'Обновление прав'], correctIndex: 0, tip: 'Итоговые уровни' },
	{ q: 'Какая роль у Feeders?', options: ['Определяют активные клетки для правил', 'Импорт CSV', 'UI навигация', 'MDX фильтрация'], correctIndex: 0, tip: 'Производительность' },
	{ q: 'Что такое PAW Book?', options: ['Набор панелей/видов', 'Резервная копия', 'Правило', 'TI-процесс'], correctIndex: 0, tip: 'Книга с листами' },
	{ q: 'TM1 поддерживает расчет по требованию?', options: ['Да', 'Нет', 'Только в PAfE', 'Только в PAW'], correctIndex: 0, tip: 'Lazy calculation' },
	{ q: 'С помощью чего делаем расписание запуска TI?', options: ['Chore', 'Rule', 'Subset', 'MDX'], correctIndex: 0, tip: 'Планировщик' },
	{ q: 'Где удобно вводить плановые данные?', options: ['PAfE/PAW', 'БД напрямую', 'MDX окно', 'TI лог'], correctIndex: 0, tip: 'Excel и Web' },
	{ q: 'Что лучше для динамических подсетов?', options: ['MDX', 'TI', 'Rules', 'CSV'], correctIndex: 0, tip: 'MDX выражения' },
	{ q: 'Какой файл хранит логи сервера?', options: ['tm1server.log', 'tm1process.log', 'tm1mdx.log', 'tm1access.log'], correctIndex: 0, tip: 'Основной лог' },
	{ q: 'Чем отличается Leaf от Consolidated?', options: ['Leaf — базовый элемент, Consolidated — агрегат', 'Разницы нет', 'Оба базовые', 'Оба агрегаты'], correctIndex: 0, tip: 'Иерархии' },
];

// Экспорт в глобальную область
window.QUESTIONS_DB = QUESTIONS_DB;
